// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_base.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommonRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Timeout              int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRequest) Reset()         { *m = CommonRequest{} }
func (m *CommonRequest) String() string { return proto.CompactTextString(m) }
func (*CommonRequest) ProtoMessage()    {}
func (*CommonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dd1f534c760321e, []int{0}
}

func (m *CommonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRequest.Unmarshal(m, b)
}
func (m *CommonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRequest.Marshal(b, m, deterministic)
}
func (m *CommonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRequest.Merge(m, src)
}
func (m *CommonRequest) XXX_Size() int {
	return xxx_messageInfo_CommonRequest.Size(m)
}
func (m *CommonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRequest proto.InternalMessageInfo

func (m *CommonRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *CommonRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CommonRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type CommonResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dd1f534c760321e, []int{1}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonRequest)(nil), "example.CommonRequest")
	proto.RegisterType((*CommonResponse)(nil), "example.CommonResponse")
}

func init() { proto.RegisterFile("example_base.proto", fileDescriptor_8dd1f534c760321e) }

var fileDescriptor_8dd1f534c760321e = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xbf, 0x8a, 0x83, 0x40,
	0x10, 0x87, 0xf1, 0x3c, 0xf5, 0x1c, 0xb8, 0x10, 0x06, 0x02, 0xa6, 0x13, 0x2b, 0xab, 0x34, 0x81,
	0x3c, 0x40, 0x52, 0xd9, 0x6e, 0x99, 0x14, 0xb2, 0xba, 0x43, 0x10, 0xb2, 0xce, 0xc4, 0x5d, 0x21,
	0x8f, 0x1f, 0x5c, 0xb4, 0xfb, 0xfd, 0x81, 0x8f, 0x0f, 0x90, 0x3e, 0xda, 0xca, 0x8b, 0xda, 0x4e,
	0x3b, 0x3a, 0xc9, 0xc4, 0x9e, 0x31, 0x5b, 0xb7, 0xea, 0x01, 0xff, 0x37, 0xb6, 0x96, 0x47, 0x45,
	0xef, 0x99, 0x9c, 0xc7, 0x23, 0xfc, 0xf9, 0x49, 0xf7, 0xd4, 0x0e, 0xa6, 0x88, 0xca, 0xa8, 0xce,
	0x55, 0x16, 0x7a, 0x63, 0xf0, 0x00, 0xa9, 0x16, 0x59, 0x8e, 0x9f, 0x70, 0x24, 0x5a, 0xa4, 0x31,
	0x58, 0x40, 0xe6, 0x07, 0x4b, 0x3c, 0xfb, 0x22, 0x2e, 0xa3, 0x3a, 0x56, 0x5b, 0xad, 0x2e, 0xb0,
	0xdb, 0xe0, 0x4e, 0x78, 0x74, 0x84, 0x08, 0xbf, 0x3d, 0x1b, 0x0a, 0xe4, 0x44, 0x85, 0x8c, 0x7b,
	0x88, 0xad, 0x7b, 0xae, 0xcc, 0x25, 0x5e, 0xf3, 0xfb, 0xe6, 0xd7, 0xa5, 0xc1, 0xf7, 0xfc, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xfd, 0xbe, 0x3c, 0xd4, 0xc5, 0x00, 0x00, 0x00,
}
