// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_service.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfoRequest struct {
	Base                 *CommonRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId               int64          `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Country              string         `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdab94845fc2b7e8, []int{0}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetBase() *CommonRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *UserInfoRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfoRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type UserInfoResponse struct {
	Base                 *CommonResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Status               int32           `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdab94845fc2b7e8, []int{1}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetBase() *CommonResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *UserInfoResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*UserInfoRequest)(nil), "example.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "example.UserInfoResponse")
}

func init() { proto.RegisterFile("example_service.proto", fileDescriptor_bdab94845fc2b7e8) }

var fileDescriptor_bdab94845fc2b7e8 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0xb6, 0x26, 0xf6, 0x09, 0x2a, 0x0f, 0x4c, 0x63, 0xbc, 0x84, 0x9c, 0x82, 0xc2, 0x16,
	0x2a, 0x78, 0x57, 0xe9, 0xa1, 0x37, 0x89, 0x88, 0xe0, 0xa5, 0x24, 0xed, 0x6b, 0x08, 0x34, 0xd9,
	0x98, 0xdd, 0x15, 0xfb, 0x1b, 0xfc, 0xd3, 0x92, 0xec, 0xae, 0xe2, 0x47, 0x8f, 0x33, 0x3b, 0xb3,
	0x33, 0xcc, 0x83, 0x33, 0x7a, 0xcf, 0xaa, 0x66, 0x43, 0x0b, 0x41, 0xed, 0x5b, 0xb9, 0x24, 0xd6,
	0xb4, 0x5c, 0x72, 0xf4, 0x0c, 0x1d, 0x5e, 0x14, 0x9c, 0x17, 0x1b, 0x9a, 0xf4, 0x74, 0xae, 0xd6,
	0x13, 0xaa, 0x1a, 0xb9, 0xd5, 0xaa, 0x10, 0xad, 0x39, 0xcf, 0x84, 0x71, 0xc6, 0x0d, 0x9c, 0x3c,
	0x09, 0x6a, 0xe7, 0xf5, 0x9a, 0xa7, 0xf4, 0xaa, 0x48, 0x48, 0xbc, 0x84, 0x61, 0x27, 0x08, 0x9c,
	0xc8, 0x49, 0x8e, 0xa6, 0x3e, 0x33, 0x2e, 0x76, 0xcf, 0xab, 0x8a, 0xd7, 0x46, 0x95, 0xf6, 0x1a,
	0x1c, 0x83, 0xa7, 0x04, 0xb5, 0x8b, 0x72, 0x15, 0xec, 0x47, 0x4e, 0x32, 0x48, 0xdd, 0x0e, 0xce,
	0x57, 0x18, 0x80, 0xb7, 0xe4, 0xaa, 0x96, 0xed, 0x36, 0x18, 0x44, 0x4e, 0x32, 0x4a, 0x2d, 0x8c,
	0x9f, 0xe1, 0xf4, 0x3b, 0x51, 0x34, 0xbc, 0x16, 0x84, 0x57, 0x3f, 0x22, 0xc7, 0x7f, 0x22, 0xb5,
	0xcc, 0x64, 0xfa, 0xe0, 0x0a, 0x99, 0x49, 0x25, 0xfa, 0xc8, 0x83, 0xd4, 0xa0, 0xe9, 0x87, 0x03,
	0xc7, 0x33, 0x6d, 0x7c, 0xd4, 0xeb, 0xe0, 0x0d, 0x0c, 0x1f, 0xca, 0xba, 0x40, 0x9f, 0xe9, 0x5d,
	0x98, 0xdd, 0x85, 0xcd, 0xba, 0x5d, 0xc2, 0x1d, 0x3c, 0xde, 0xc2, 0xa1, 0xed, 0x88, 0xc1, 0x57,
	0x9b, 0x5f, 0x43, 0x85, 0xe7, 0xff, 0xbc, 0xe8, 0xa6, 0xf1, 0xde, 0xdd, 0xe8, 0xc5, 0x1e, 0x25,
	0x77, 0xfb, 0xdf, 0xaf, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xda, 0x17, 0x2a, 0xbd, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleServiceClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
}

type exampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleServiceClient(cc *grpc.ClientConn) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.ExampleService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleServiceClient) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/example.ExampleService/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceServer is the server API for ExampleService service.
type ExampleServiceServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	UserInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error)
}

// UnimplementedExampleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExampleServiceServer struct {
}

func (*UnimplementedExampleServiceServer) Ping(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedExampleServiceServer) UserInfo(ctx context.Context, req *UserInfoRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleService_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleService/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).UserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ExampleService_Ping_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _ExampleService_UserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example_service.proto",
}
